spring:
  application:
    name: voting-system
  datasource:
#    url: spring.datasource.url=jdbc:mysql://localhost:3306/votingsystem
    url: jdbc:postgresql://localhost:5432/votingsystem
    username: postgres
    password: postgres
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.springimplant.votingsystem.util.CustomPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true 
  security:
    user:
      name: foo
      password: bar
server:
  port: 8082
#  ssl:
#    key-alias: server
#    key-password: changeit
#    key-store: classpath:server
#    key-store-provider: SUN
#    key-store-type: JKS
#    client-auth: want

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] - %msg%n'
  level:
   '[org.hibernate]': info
   '[org.springframework.web]': info
   '[org.hibernate.sql]': debug
   '[org.hibernate.type]': trace
   '[org.hibernate.type.descriptor.sql]': trace

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
     defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: localhost
    ip-address: 127.0.0.1