server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       format_sql: true
    open-in-view: false