server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       format_sql: true
    open-in-view: false
  profiles:
    active: local
  datasource:
      tomcat:
       connection-properties: stringtype=unspecified
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
jasypt:
  encryptor:
    password: springimplant
    