server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       format_sql: true
    open-in-view: false
  profiles:
    active: local
  datasource:
      tomcat:
       connection-properties: stringtype=unspecified
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] - %msg%n'
  level:
    '[org.hibernate]': info
    '[org.springframework.web]': info
    '[org.hibernate.sql]': debug
    '[org.hibernate.type]': trace
    '[org.hibernate.type.descriptor.sql]': trace

jasypt:
  encryptor:
    password: springimplant