management:
  endpoint:
    env:
      enabled: true    health:      enabled: true      show-details: always    beans:      enabled: true    metrics:      enabled: true    mappings:      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'  info:    env:      enabled: true
spring:
  profiles: dev
server:  port: 8001
---
spring:  profiles: test
server:  port: 9001